use_frameworks!

target 'YYDownLoadCenter_Example' do
  pod 'YYDownLoadCenter', :path => '../'

  target 'YYDownLoadCenter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
